# Generated by Django 3.0.5 on 2020-06-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprisesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='enterprises', to='enterprisesapp.Skill'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
