# Generated by Django 3.1.1 on 2020-09-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprisesapp', '0003_auto_20200903_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fr',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
