# Generated by Django 3.1.4 on 2021-01-01 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enterprisesapp', '0004_auto_20200903_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('enterprise_saved_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_saved_search', to='enterprisesapp.enterprise')),
            ],
            options={
                'verbose_name_plural': 'Enterprise Saved Searches',
            },
        ),
    ]
