# Generated by Django 3.1.4 on 2021-01-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprisesapp', '0005_companysavedsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysavedsearch',
            name='enterprise_saved_id',
        ),
        migrations.AddField(
            model_name='companysavedsearch',
            name='enterprise_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
