# Generated by Django 3.1.4 on 2021-01-01 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enterprisesapp', '0006_auto_20210101_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enterprise_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Enterprise Saved Searches',
            },
        ),
        migrations.DeleteModel(
            name='CompanySavedSearch',
        ),
    ]
